/**
 * Expansion bestiary seed data: where the new monsters (MOB_TEMPLATES additions tagged
 * "Expansion bestiary" in src/server/mobs.ts) spawn, what they drop, and which of them
 * belong in the endgame rift's population pool. Pure data — the seed orchestrator
 * (seed.ts) consumes these via the same idempotent upsert paths it uses for the other
 * area_mobs / loot_entry content, and applies EXPANSION_RIFT_POOL to DUNGEONS.rift.
 *
 * Loot follows the established loot_entry shape (see seedLoot in seed.ts and
 * src/server/drop-table.ts): an 'always' gold row, a weighted 'main' roll where the
 * is_nothing row is the blank, an optional 'rare' rune-shard row gated by `chance`,
 * and 'gear' rows where `chance` triggers one uniform pick from the group.
 */

/** Overworld spawn rosters for the expansion monsters (areas from src/shared/areas.ts). */
export const EXPANSION_AREA_MOBS: { areaId: string; templateId: string; count: number }[] = [
  // Gloomwood Wilderness (L2-5)
  { areaId: 'wilderness', templateId: 'thistle_kobold', count: 4 },
  { areaId: 'wilderness', templateId: 'mosshide_orc', count: 3 },
  { areaId: 'wilderness', templateId: 'shadowmaw_bear', count: 2 },
  // Rotfen Marsh (L8-12)
  { areaId: 'marsh', templateId: 'rotfen_naga', count: 3 },
  { areaId: 'marsh', templateId: 'fen_ettin', count: 2 },
  // Emberdeep Mines (L12-16)
  { areaId: 'mines', templateId: 'gloomcap_myconid', count: 3 },
  { areaId: 'mines', templateId: 'basalt_basilisk', count: 2 },
  // Frostpeak Pass (L15-20)
  { areaId: 'frostpeak', templateId: 'gnarlfang_lycan', count: 3 },
  { areaId: 'frostpeak', templateId: 'crag_manticore', count: 2 },
  // The Sundered Wastes (L20-26)
  { areaId: 'sundered_wastes', templateId: 'riftwing_harpy', count: 3 },
  { areaId: 'sundered_wastes', templateId: 'voidscale_drake', count: 2 },
  // The Blighted Spire (L27-32)
  { areaId: 'blighted_spire', templateId: 'blightgore_minotaur', count: 2 },
];

/**
 * loot_entry rows for the expansion monsters. Item ids are all pre-existing content
 * (materials from seed.ts MATERIALS, equipment from src/shared/equipment.ts); gold ranges
 * and material weights are tuned against same-level neighbours in src/server/loot.ts.
 * The Wastes/Spire have no zone material, so their mobs roll rune shards on the main
 * table instead — consistent with those zones' gold-and-shards economy.
 */
export const EXPANSION_LOOT: {
  mobTemplateId: string;
  grp: string;
  itemId: string;
  weight: number;
  minQty: number;
  maxQty: number;
  isNothing: 0 | 1;
  chance: number;
}[] = [
  // Thistle Kobold (L2) — bat-tier pocket change and the odd bone.
  {
    mobTemplateId: 'thistle_kobold',
    grp: 'always',
    itemId: 'gold',
    weight: 1,
    minQty: 1,
    maxQty: 5,
    isNothing: 0,
    chance: 0,
  },
  {
    mobTemplateId: 'thistle_kobold',
    grp: 'main',
    itemId: 'bone',
    weight: 50,
    minQty: 1,
    maxQty: 1,
    isNothing: 0,
    chance: 0,
  },
  {
    mobTemplateId: 'thistle_kobold',
    grp: 'main',
    itemId: 'gold',
    weight: 50,
    minQty: 1,
    maxQty: 1,
    isNothing: 1,
    chance: 0,
  },

  // Mosshide Orc (L4) — wolf-tier gold plus starter gear.
  {
    mobTemplateId: 'mosshide_orc',
    grp: 'always',
    itemId: 'gold',
    weight: 1,
    minQty: 3,
    maxQty: 10,
    isNothing: 0,
    chance: 0,
  },
  {
    mobTemplateId: 'mosshide_orc',
    grp: 'main',
    itemId: 'bone',
    weight: 55,
    minQty: 1,
    maxQty: 2,
    isNothing: 0,
    chance: 0,
  },
  {
    mobTemplateId: 'mosshide_orc',
    grp: 'main',
    itemId: 'gold',
    weight: 45,
    minQty: 1,
    maxQty: 1,
    isNothing: 1,
    chance: 0,
  },
  {
    mobTemplateId: 'mosshide_orc',
    grp: 'gear',
    itemId: 'rusty_sword',
    weight: 1,
    minQty: 1,
    maxQty: 1,
    isNothing: 0,
    chance: 0.3,
  },
  {
    mobTemplateId: 'mosshide_orc',
    grp: 'gear',
    itemId: 'leather_armor',
    weight: 1,
    minQty: 1,
    maxQty: 1,
    isNothing: 0,
    chance: 0.3,
  },

  // Shadowmaw Bear (L5) — a hide animal: pelts for the tanner (warm_hides quest fodder).
  {
    mobTemplateId: 'shadowmaw_bear',
    grp: 'always',
    itemId: 'gold',
    weight: 1,
    minQty: 4,
    maxQty: 12,
    isNothing: 0,
    chance: 0,
  },
  {
    mobTemplateId: 'shadowmaw_bear',
    grp: 'main',
    itemId: 'wolf_pelt',
    weight: 60,
    minQty: 1,
    maxQty: 2,
    isNothing: 0,
    chance: 0,
  },
  {
    mobTemplateId: 'shadowmaw_bear',
    grp: 'main',
    itemId: 'gold',
    weight: 40,
    minQty: 1,
    maxQty: 1,
    isNothing: 1,
    chance: 0,
  },

  // Rotfen Naga (L10) — marsh economy: venom glands, slim rune-shard chance.
  {
    mobTemplateId: 'rotfen_naga',
    grp: 'always',
    itemId: 'gold',
    weight: 1,
    minQty: 10,
    maxQty: 24,
    isNothing: 0,
    chance: 0,
  },
  {
    mobTemplateId: 'rotfen_naga',
    grp: 'main',
    itemId: 'venom_gland',
    weight: 60,
    minQty: 1,
    maxQty: 2,
    isNothing: 0,
    chance: 0,
  },
  {
    mobTemplateId: 'rotfen_naga',
    grp: 'main',
    itemId: 'gold',
    weight: 40,
    minQty: 1,
    maxQty: 1,
    isNothing: 1,
    chance: 0,
  },
  {
    mobTemplateId: 'rotfen_naga',
    grp: 'rare',
    itemId: 'rune_shard',
    weight: 1,
    minQty: 1,
    maxQty: 1,
    isNothing: 0,
    chance: 0.06,
  },

  // Rotfen Ettin (L11) — marsh tank: steel-tier gear like the Fen Strangler.
  {
    mobTemplateId: 'fen_ettin',
    grp: 'always',
    itemId: 'gold',
    weight: 1,
    minQty: 16,
    maxQty: 36,
    isNothing: 0,
    chance: 0,
  },
  {
    mobTemplateId: 'fen_ettin',
    grp: 'main',
    itemId: 'venom_gland',
    weight: 55,
    minQty: 1,
    maxQty: 3,
    isNothing: 0,
    chance: 0,
  },
  {
    mobTemplateId: 'fen_ettin',
    grp: 'main',
    itemId: 'gold',
    weight: 45,
    minQty: 1,
    maxQty: 1,
    isNothing: 1,
    chance: 0,
  },
  {
    mobTemplateId: 'fen_ettin',
    grp: 'rare',
    itemId: 'rune_shard',
    weight: 1,
    minQty: 1,
    maxQty: 1,
    isNothing: 0,
    chance: 0.08,
  },
  {
    mobTemplateId: 'fen_ettin',
    grp: 'gear',
    itemId: 'steel_sword',
    weight: 1,
    minQty: 1,
    maxQty: 1,
    isNothing: 0,
    chance: 0.3,
  },
  {
    mobTemplateId: 'fen_ettin',
    grp: 'gear',
    itemId: 'steel_helm',
    weight: 1,
    minQty: 1,
    maxQty: 1,
    isNothing: 0,
    chance: 0.3,
  },

  // Gloomcap Myconid (L12) — mines economy: ember ore.
  {
    mobTemplateId: 'gloomcap_myconid',
    grp: 'always',
    itemId: 'gold',
    weight: 1,
    minQty: 10,
    maxQty: 26,
    isNothing: 0,
    chance: 0,
  },
  {
    mobTemplateId: 'gloomcap_myconid',
    grp: 'main',
    itemId: 'ember_ore',
    weight: 55,
    minQty: 1,
    maxQty: 2,
    isNothing: 0,
    chance: 0,
  },
  {
    mobTemplateId: 'gloomcap_myconid',
    grp: 'main',
    itemId: 'gold',
    weight: 45,
    minQty: 1,
    maxQty: 1,
    isNothing: 1,
    chance: 0,
  },

  // Basalt Basilisk (L15) — the mines' heavy: steel-tier gear like the Magma Crawler.
  {
    mobTemplateId: 'basalt_basilisk',
    grp: 'always',
    itemId: 'gold',
    weight: 1,
    minQty: 18,
    maxQty: 42,
    isNothing: 0,
    chance: 0,
  },
  {
    mobTemplateId: 'basalt_basilisk',
    grp: 'main',
    itemId: 'ember_ore',
    weight: 60,
    minQty: 1,
    maxQty: 3,
    isNothing: 0,
    chance: 0,
  },
  {
    mobTemplateId: 'basalt_basilisk',
    grp: 'main',
    itemId: 'gold',
    weight: 40,
    minQty: 1,
    maxQty: 1,
    isNothing: 1,
    chance: 0,
  },
  {
    mobTemplateId: 'basalt_basilisk',
    grp: 'rare',
    itemId: 'rune_shard',
    weight: 1,
    minQty: 1,
    maxQty: 1,
    isNothing: 0,
    chance: 0.08,
  },
  {
    mobTemplateId: 'basalt_basilisk',
    grp: 'gear',
    itemId: 'steel_sword',
    weight: 1,
    minQty: 1,
    maxQty: 1,
    isNothing: 0,
    chance: 0.3,
  },
  {
    mobTemplateId: 'basalt_basilisk',
    grp: 'gear',
    itemId: 'steel_armor',
    weight: 1,
    minQty: 1,
    maxQty: 1,
    isNothing: 0,
    chance: 0.3,
  },
  {
    mobTemplateId: 'basalt_basilisk',
    grp: 'gear',
    itemId: 'tower_shield',
    weight: 1,
    minQty: 1,
    maxQty: 1,
    isNothing: 0,
    chance: 0.3,
  },

  // Gnarlfang Lycan (L17) — frostpeak economy: frost cores.
  {
    mobTemplateId: 'gnarlfang_lycan',
    grp: 'always',
    itemId: 'gold',
    weight: 1,
    minQty: 16,
    maxQty: 36,
    isNothing: 0,
    chance: 0,
  },
  {
    mobTemplateId: 'gnarlfang_lycan',
    grp: 'main',
    itemId: 'frost_core',
    weight: 50,
    minQty: 1,
    maxQty: 2,
    isNothing: 0,
    chance: 0,
  },
  {
    mobTemplateId: 'gnarlfang_lycan',
    grp: 'main',
    itemId: 'gold',
    weight: 50,
    minQty: 1,
    maxQty: 1,
    isNothing: 1,
    chance: 0,
  },

  // Crag Manticore (L18) — mithril-tier gear like the Avalanche Shade.
  {
    mobTemplateId: 'crag_manticore',
    grp: 'always',
    itemId: 'gold',
    weight: 1,
    minQty: 20,
    maxQty: 42,
    isNothing: 0,
    chance: 0,
  },
  {
    mobTemplateId: 'crag_manticore',
    grp: 'main',
    itemId: 'frost_core',
    weight: 55,
    minQty: 1,
    maxQty: 2,
    isNothing: 0,
    chance: 0,
  },
  {
    mobTemplateId: 'crag_manticore',
    grp: 'main',
    itemId: 'gold',
    weight: 45,
    minQty: 1,
    maxQty: 1,
    isNothing: 1,
    chance: 0,
  },
  {
    mobTemplateId: 'crag_manticore',
    grp: 'rare',
    itemId: 'rune_shard',
    weight: 1,
    minQty: 1,
    maxQty: 2,
    isNothing: 0,
    chance: 0.1,
  },
  {
    mobTemplateId: 'crag_manticore',
    grp: 'gear',
    itemId: 'mithril_blade',
    weight: 1,
    minQty: 1,
    maxQty: 1,
    isNothing: 0,
    chance: 0.3,
  },
  {
    mobTemplateId: 'crag_manticore',
    grp: 'gear',
    itemId: 'mithril_armor',
    weight: 1,
    minQty: 1,
    maxQty: 1,
    isNothing: 0,
    chance: 0.3,
  },

  // Riftwing Harpy (L21) — the Wastes: gold plus main-table rune shards.
  {
    mobTemplateId: 'riftwing_harpy',
    grp: 'always',
    itemId: 'gold',
    weight: 1,
    minQty: 26,
    maxQty: 56,
    isNothing: 0,
    chance: 0,
  },
  {
    mobTemplateId: 'riftwing_harpy',
    grp: 'main',
    itemId: 'rune_shard',
    weight: 25,
    minQty: 1,
    maxQty: 1,
    isNothing: 0,
    chance: 0,
  },
  {
    mobTemplateId: 'riftwing_harpy',
    grp: 'main',
    itemId: 'gold',
    weight: 75,
    minQty: 1,
    maxQty: 1,
    isNothing: 1,
    chance: 0,
  },

  // Voidscale Drake (L24) — endgame mithril gear and shards.
  {
    mobTemplateId: 'voidscale_drake',
    grp: 'always',
    itemId: 'gold',
    weight: 1,
    minQty: 32,
    maxQty: 70,
    isNothing: 0,
    chance: 0,
  },
  {
    mobTemplateId: 'voidscale_drake',
    grp: 'main',
    itemId: 'rune_shard',
    weight: 30,
    minQty: 1,
    maxQty: 2,
    isNothing: 0,
    chance: 0,
  },
  {
    mobTemplateId: 'voidscale_drake',
    grp: 'main',
    itemId: 'gold',
    weight: 70,
    minQty: 1,
    maxQty: 1,
    isNothing: 1,
    chance: 0,
  },
  {
    mobTemplateId: 'voidscale_drake',
    grp: 'gear',
    itemId: 'mithril_blade',
    weight: 1,
    minQty: 1,
    maxQty: 1,
    isNothing: 0,
    chance: 0.3,
  },
  {
    mobTemplateId: 'voidscale_drake',
    grp: 'gear',
    itemId: 'mithril_armor',
    weight: 1,
    minQty: 1,
    maxQty: 1,
    isNothing: 0,
    chance: 0.3,
  },
  {
    mobTemplateId: 'voidscale_drake',
    grp: 'gear',
    itemId: 'runed_band',
    weight: 1,
    minQty: 1,
    maxQty: 1,
    isNothing: 0,
    chance: 0.3,
  },

  // Blightgore Minotaur (L29) — Spire elite: the richest non-boss gear group.
  {
    mobTemplateId: 'blightgore_minotaur',
    grp: 'always',
    itemId: 'gold',
    weight: 1,
    minQty: 45,
    maxQty: 95,
    isNothing: 0,
    chance: 0,
  },
  {
    mobTemplateId: 'blightgore_minotaur',
    grp: 'main',
    itemId: 'rune_shard',
    weight: 35,
    minQty: 1,
    maxQty: 2,
    isNothing: 0,
    chance: 0,
  },
  {
    mobTemplateId: 'blightgore_minotaur',
    grp: 'main',
    itemId: 'gold',
    weight: 65,
    minQty: 1,
    maxQty: 1,
    isNothing: 1,
    chance: 0,
  },
  {
    mobTemplateId: 'blightgore_minotaur',
    grp: 'gear',
    itemId: 'mithril_blade',
    weight: 1,
    minQty: 1,
    maxQty: 1,
    isNothing: 0,
    chance: 0.35,
  },
  {
    mobTemplateId: 'blightgore_minotaur',
    grp: 'gear',
    itemId: 'mithril_armor',
    weight: 1,
    minQty: 1,
    maxQty: 1,
    isNothing: 0,
    chance: 0.35,
  },
  {
    mobTemplateId: 'blightgore_minotaur',
    grp: 'gear',
    itemId: 'tower_shield',
    weight: 1,
    minQty: 1,
    maxQty: 1,
    isNothing: 0,
    chance: 0.35,
  },
  {
    mobTemplateId: 'blightgore_minotaur',
    grp: 'gear',
    itemId: 'runed_band',
    weight: 1,
    minQty: 1,
    maxQty: 1,
    isNothing: 0,
    chance: 0.35,
  },
];

/**
 * Expansion templates that suit the endgame rift's chaotic cross-act roster (its existing
 * pool spans L3-22, so the early-game fodder stays out). The orchestrator merges these
 * into DUNGEONS.rift's pool at runtime.
 */
export const EXPANSION_RIFT_POOL: string[] = [
  'gloomcap_myconid',
  'basalt_basilisk',
  'gnarlfang_lycan',
  'crag_manticore',
  'riftwing_harpy',
  'voidscale_drake',
  'blightgore_minotaur',
];
